[remote.github]
owner = "deskulpt-apps"
repo  = "Deskulpt"

[git]
commit_parsers = [
  { message = "^feat", group = "<!-- A -->ğŸš€ Features" },
  { message = "^perf", group = "<!-- B -->âš¡ Performance" },
  { message = "^fix", group = "<!-- C -->ğŸ› Bug Fixes" },
  { message = "^doc", group = "<!-- D -->ğŸ“š Documentation" },
  { message = "^refactor", group = "<!-- E -->ğŸšœ Refactor" },
  { message = "^test", group = "<!-- F -->ğŸ§ª Testing" },
  { message = "^style", group = "<!-- G -->ğŸ¨ Styling" },
  { message = "^release", skip = true },
  { message = ".*", group = "<!-- H -->âš™ï¸ Miscellaneous" },
]
conventional_commits = true
filter_unconventional = true
sort_commits = "newest"
split_commits = false

[changelog]
trim = true

# https://git-cliff.org/docs/category/templating
body = """
{%- macro print_commit(commit) -%}
  - {% if commit.scope %}*({{ commit.scope }})* {% endif %}\
    {{ commit.message | split(pat="\n") | first | trim }}\
    {% if commit.remote.username %} by @{{ commit.remote.username }}{%- endif -%}
    {% raw %}\n{% endraw -%}
{%- endmacro -%}

This is the {{ version }} release of Deskulpt.{% raw %}\n\n{% endraw -%}

{%- if github.contributors | length != 0 -%}
  This release was made possible by PR contributions from{% raw %} {% endraw -%}
  {%- for contributor in github.contributors -%}
    @{{ contributor.username }}{% if not loop.last %}, {% else %}.{% endif %}
  {%- endfor -%}
  {% raw %}\n\n{% endraw -%}
{%- endif -%}

## What's Changed{% raw %}\n\n{% endraw -%}

**Full changelog:** https://github.com/{{ remote.github.owner }}/{{ remote.github.repo }}/compare/{{ previous.version }}..{{ version }}{% raw %}\n\n{% endraw -%}

{%- if commits | filter(attribute="breaking", value=true) | length != 0 -%}
  ### ğŸ’¥ BREAKING CHANGES{% raw %}\n\n{% endraw -%}
  {%- for commit in commits | filter(attribute="breaking", value=true) -%}
    {{ self::print_commit(commit=commit) }}
  {%- endfor -%}\
  {% raw %}\n{% endraw -%}
{%- endif -%}

{%- for group, commits in commits | filter(attribute="breaking", value=false) | sort(attribute="group") | group_by(attribute="group") -%}
  {%- if commits | length != 0 -%}
    ### {{ group | striptags | trim | upper_first }}{% raw %}\n\n{% endraw -%}
    {%- for commit in commits -%}
      {{ self::print_commit(commit=commit) }}
    {%- endfor -%}
    {% raw %}\n{% endraw -%}
  {%- endif -%}
{%- endfor -%}

<!-- Generated by git-cliff -->
"""
